version: '3.1'

services:

  server:
    image: wa2-g15:latest
    container_name: server
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://TODO_IP:5432/project_db
      - SPRING_DATASOURCE_USERNAME=postgres_g15
      - SPRING_DATASOURCE_PASSWORD=webapp_g15
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - SPRING_APPLICATION_NAME=springboot-keycloak
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://TODO_IP:8081/realms/SpringBootKeycloak
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://TODO_IP:8081/realms/SpringBootKeycloak/protocol/openid-connect/certs
      - JWT_AUTH_CONVERTER_RESOURCE_ID=springboot-keycloak-client
      - JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE=preferred_username
